[2025-01-07T15:13:52.055+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-07T15:13:52.148+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.is_inaccurate manual__2025-01-07T15:13:46.939703+00:00 [queued]>
[2025-01-07T15:13:52.162+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.is_inaccurate manual__2025-01-07T15:13:46.939703+00:00 [queued]>
[2025-01-07T15:13:52.163+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-07T15:13:52.180+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): is_inaccurate> on 2025-01-07 15:13:46.939703+00:00
[2025-01-07T15:13:52.185+0000] {standard_task_runner.py:63} INFO - Started process 3081 to run task
[2025-01-07T15:13:52.188+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'is_inaccurate', 'manual__2025-01-07T15:13:46.939703+00:00', '--job-id', '877', '--raw', '--subdir', 'DAGS_FOLDER/das_ytb.py', '--cfg-path', '/tmp/tmpqpxmiy5n']
[2025-01-07T15:13:52.191+0000] {standard_task_runner.py:91} INFO - Job 877: Subtask is_inaccurate
[2025-01-07T15:13:52.243+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.is_inaccurate manual__2025-01-07T15:13:46.939703+00:00 [running]> on host 4ff5b0867c78
[2025-01-07T15:13:52.468+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='is_inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T15:13:46.939703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T15:13:46.939703+00:00'
[2025-01-07T15:13:52.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-07T15:13:52.480+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-07T15:13:52.482+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', " echo 'inaccurate'"]
[2025-01-07T15:13:52.491+0000] {subprocess.py:86} INFO - Output:
[2025-01-07T15:13:52.502+0000] {subprocess.py:93} INFO - inaccurate
[2025-01-07T15:13:52.504+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-07T15:13:52.505+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-07T15:13:52.533+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=is_inaccurate, run_id=manual__2025-01-07T15:13:46.939703+00:00, execution_date=20250107T151346, start_date=20250107T151352, end_date=20250107T151352
[2025-01-07T15:13:52.564+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-07T15:13:52.581+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T15:13:52.586+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
