[2025-01-09T16:28:18.959+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-09T16:28:19.018+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_geolocation manual__2025-01-09T16:27:04.114165+00:00 [queued]>
[2025-01-09T16:28:19.035+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_geolocation manual__2025-01-09T16:27:04.114165+00:00 [queued]>
[2025-01-09T16:28:19.036+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-09T16:28:19.065+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_geolocation> on 2025-01-09 16:27:04.114165+00:00
[2025-01-09T16:28:19.076+0000] {standard_task_runner.py:63} INFO - Started process 3705 to run task
[2025-01-09T16:28:19.090+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_geolocation', 'manual__2025-01-09T16:27:04.114165+00:00', '--job-id', '923', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmp2spwzyi0']
[2025-01-09T16:28:19.097+0000] {standard_task_runner.py:91} INFO - Job 923: Subtask transform.transform_dim_geolocation
[2025-01-09T16:28:19.187+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_geolocation manual__2025-01-09T16:27:04.114165+00:00 [running]> on host 683e2530fb40
[2025-01-09T16:28:19.766+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_geolocation' AIRFLOW_CTX_EXECUTION_DATE='2025-01-09T16:27:04.114165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-09T16:27:04.114165+00:00'
[2025-01-09T16:28:19.768+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-09T16:28:19.812+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-01-09T16:28:19.853+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-09T16:28:29.685+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-01-09T16:28:32.395+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào dim_geolocation
[2025-01-09T16:28:32.434+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-09T16:28:32.435+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-09T16:28:32.453+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_geolocation, run_id=manual__2025-01-09T16:27:04.114165+00:00, execution_date=20250109T162704, start_date=20250109T162819, end_date=20250109T162832
[2025-01-09T16:28:32.553+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-09T16:28:32.618+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-09T16:28:32.623+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
