[2025-01-08T07:41:09.236+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-08T07:41:09.295+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_customers manual__2025-01-08T07:40:03.706833+00:00 [queued]>
[2025-01-08T07:41:09.314+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e_commerce_dw_etl.transform.transform_dim_customers manual__2025-01-08T07:40:03.706833+00:00 [queued]>
[2025-01-08T07:41:09.316+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-08T07:41:09.349+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform.transform_dim_customers> on 2025-01-08 07:40:03.706833+00:00
[2025-01-08T07:41:09.360+0000] {standard_task_runner.py:63} INFO - Started process 3097 to run task
[2025-01-08T07:41:09.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'e_commerce_dw_etl', 'transform.transform_dim_customers', 'manual__2025-01-08T07:40:03.706833+00:00', '--job-id', '910', '--raw', '--subdir', 'DAGS_FOLDER/e_commerce_dw_dag.py', '--cfg-path', '/tmp/tmpi9odgo09']
[2025-01-08T07:41:09.377+0000] {standard_task_runner.py:91} INFO - Job 910: Subtask transform.transform_dim_customers
[2025-01-08T07:41:09.482+0000] {task_command.py:426} INFO - Running <TaskInstance: e_commerce_dw_etl.transform.transform_dim_customers manual__2025-01-08T07:40:03.706833+00:00 [running]> on host 4ff5b0867c78
[2025-01-08T07:41:09.662+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='e_commerce_dw_etl' AIRFLOW_CTX_TASK_ID='transform.transform_dim_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-01-08T07:40:03.706833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-08T07:40:03.706833+00:00'
[2025-01-08T07:41:09.664+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-08T07:41:09.712+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-01-08T07:41:09.770+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers/common/sql/hooks/sql.py:263 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-01-08T07:41:12.283+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2025-01-08T07:41:20.364+0000] {logging_mixin.py:188} INFO - Đã transform và lưu dữ liệu vào dim_customers
[2025-01-08T07:41:20.382+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-01-08T07:41:20.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-08T07:41:20.397+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=e_commerce_dw_etl, task_id=transform.transform_dim_customers, run_id=manual__2025-01-08T07:40:03.706833+00:00, execution_date=20250108T074003, start_date=20250108T074109, end_date=20250108T074120
[2025-01-08T07:41:20.464+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-08T07:41:20.491+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-08T07:41:20.494+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
